isomerpages/moe-catholichigh

_config.yml
index.md

found a error. on intelligent Bob. link and Site Description update

Url Fix and Site Description update

---

_non-academic/Character Education/Education and Career Guidance.md
_non-academic/Character Education/Sexuality Education.md

Update of CE and Broken Links

---

_student-development/Character Education/Sexuality Education Programme.md

Removal of duplicate text" At CATHOLIC HIGH SCHOOL, the following lessons from the Sexuality Education Programme will be taught in 2023:"

Update file: Sexuality Education Programme.md

---

index.md

include DSA

---

_connect-with-us/Parents Bulletin (Sec).md

Changing the URL to 2023 Term 2 Parent Bulletin to updated Parent bulletin that is being updated and requested by Se yean.

Update file: Parents Bulletin (Sec).md

---

index.md

Infobar with text cleared by VP Tan kelly in WA group to go live 20 April 2023

Put infobar for easier access to 2023 DSA access

---

_prospective-students/Sec Admission/Sec Admission & Fees.md

Update of Sec admission page

---

_primary/Staff Contact.md
_secondary/Awards & Achievements/Overview.md
_secondary/Distinctive Programmes/Passion Pursuit (Elective) (SP & IP).md

Update Staff List (Pri)

---

_secondary/Staff Contact.md

…md","userId":"1032"}
Update to chua_tock_hai@moe.edu.sg
Minus of the extra _a

Update of Secondary STaff contact Chua Tock Hai

---

_secondary/Staff Contact.md

Fredrik to pull for the changes made by Yian hoon

Staff contact changes (Secondary)

---

_primary/Staff Contact.md

Update Teacher ren_jin@moe.edu.sg to ren_jing@moe.edu.sg

Update  Primary Staff Contact list.

---

_data/navigation.yml
_secondary/FAQs (Secondary Section).md

Add </a> at the end of the <a href> for proper closure. otherwise it will appears a text "</a> after the image which is happening now.

adding </a> at the end of <a href>

---

_advertisement/School Canteen (Primary).md
_primary/Staff Contact.md

Update Canteen Register Date and Primary Staff List

Update Canteen Register Date and Primary Staff List

---

_data/navigation.yml

Added Student Google Workspace and Sch Helpdesk in to Quick Link

Added Student Google Workspace and Sch Helpdesk in to Quick Link

---

_prospective-students/Admission to IP Year 3.md

Changes made in prep for 01 Sept 2023 application window opening

Application for Admission to Year 3 Integrated Programme in 2024

---

_connect-with-us/Parents Bulletin (Sec).md
pages/example.md

Add Link to CHS Sec Parent Bulletin Term 4

CHS Parent Bulletin Term 4

---

_primary/Staff Contact.md

Rmoved Ng Lian Huay, Added Chan Yin Kong

Update Primary Staff List

---

_academic/Gifted Education Programme/Signature Programmes.md

Update GEP Signature Programes

---

index.md

Removed Open House and family day
added Community Bursary Award 2024

Home Main page update

---

_advertisement/School Canteen (Primary).md
_secondary/Talent Development/Music Elective Programme.md

Updated Selection Exercise info for 2024 and the corresponding dates provided according to the email from Claire

Update to TDP MEP Page 

---

_data/footer.yml
_secondary/FAQs (Secondary Section).md

On FAQ page
on main page footer

Updating Askgov link to https://ask.gov.sg/chs

---

_secondary/Staff Contact.md

After all RT and updated with Sharon Tan's new Icon email

Final Staff Contact List Secondary

---

_advertisement/School Canteen (Primary).md
_primary/Staff Contact.md

Update new FAJT contact

---

_advertisement/School Canteen (Primary).md

fix spelling error from Staff to Staff on Canteen page

fix spelling error

---

_secondary/Staff Contact.md

Wang Yi Chun email @ HOD/LH/SH/LT/ST
Removal of Jonathan Lim Leap 
Updating of FAJT emails Chua Tock hai, Dave Sim

Staff Contact (Secondary)

---

_data/footer.yml
pages/contact-us.md

Updated GO operating hr from  7-6pm to 7-5pm

Updated GO operating hr

---

_advertisement/School Canteen (Primary).md

Update School Canteen (Primary)

Update School Canteen (Primary)

---

_connect-with-us/Parents Bulletin (Sec).md
_secondary/Staff Contact.md

Secondary Term 2 parent bulletin + Staff contact update for term 2

Secondary Term 2 parent bulletin + Staff contact update for term 2

---

_about/Our CHS Campus.md
_secondary/Staff Contact.md
pages/CHS Academic Info.md

Eugene Chua left school
Updating of broken link in CHS academics info under open house
Update of staging link in our campus page

Secondary staff contact  update plus other minor change

---

_advertisement/School Canteen (Primary).md

1. Added: CHINESE CUISINE STALL (Breakfast Items) 
2. Modify CHINESE NOODLE STALL Date from  30 April to 30 June 2024

CHS Primary Canteen Advertisement update

---

_prospective-students/Direct School Admission (DSA).md

DSA moe DSA hyperllink update

---

_prospective-students/Direct School Admission (DSA).md
index.md

Update Announcement to mention Principal's Talk timing 
+ DSA URL to make it clickable. (minor edit).... URL is correct.

Update Annoucement to mention Principal's Talk timing 

---

_prospective-students/Open House.md

Update as there is public query

Update open house page to include P sharing timing 

---

_connect-with-us/Parents Bulletin (Sec).md
_secondary/Staff Contact.md

Uploading of 2024 Term 3 Parent Bulletin Secondary + Removal of David Whet from Staff Contact Secondary

Uploading of 2024 Term 3 Parent Bulletin Secondary + Removal of David Whet from Staff Contact Secondary

---

_advertisement/School Canteen (Primary).md

Removed the advertisement for Chinese Noodle Stall as the stall had been taken

updated CHS Canteen Advertisement

---

_secondary/Staff Contact.md

To remove:
Mrs Sharon Tan Huizhen
4-2 Mr Muhammad Norhafiz Bin Samsudin: muhammad_norhafiz_samsudin@moe.edu.sg
To add:
Mr Tang Kum Leong James: tang_kum_leong_a@moe.edu.sg (under "Teaching Staff (2024)")
1-8 Mr Tan Nian Kai: tan_nian_kai@moe.edu.sg
2-3 Mr Fok Chee Wel Ernest: fok_chee_wel@moe.edu.sg
4-2 Mdm Chng Xun Qi: chng_xun_qi@moe.edu.sg
4-5 Ms Sonia How Kai Tong: how_kai_tong_sonia@moe.edu.sg
4-6 Mr Tan Wai Mun Danny: danny_tan_wai_mun@moe.edu.sg
Staging URL: https://staging-lite.d38wyvdzolkra3.amplifyapp.com/secondary/staff-contact/

To update the Staff Contact list for CHS Sec

---

_secondary/Staff Contact.md

Staff Contact Sec Changes to Amy + James Tang as school teaching staff 2024

Staff Contact Sec Changes to Amy + James Tang as school teaching staff 2024

---

pages/privacy.md
pages/terms-of-use.md

Updating of Terms of Use and Privacy Statement

Updating of Terms of Use and Privacy Statement

---

_prospective-students/Admission to IP Year 3.md

Request from Ho Seok Lay. It is for updating information on the "Admission to IP Year 3" webpage.

To update the "Admission to IP Year 3" webpage

---

_about/Partnerships.md

Added "Catholic Parents Community" with the hyperlink (https://www.facebook.com/groups/240335456548718)

Partnerships webpage

---

_advertisement/School Canteen (Secondary).md

School Canteen application update as of 24 Sept 2024

School Canteen Advertisement

---

_advertisement/School Canteen (Secondary).md

Latest one that content is find

School Canteen Advertisement 

---

_prospective-students/Admission to IP Year 3.md

To change links (SG form) for Admission to IP Year 3 webpage

---

_connect-with-us/Contact School & Services/Overview.md
_secondary/Staff Contact.md

Removal of VP Tan Kelly, Updating VP 2 and VP 3 to VP 1 and VP 2, Standardisation of no spacing for Designation, 
Adding space for between Email and the Bracketed-information i.e Email: chs@moe.edu.sg (including DSA-related queries)

Secondary Staff contact list update + Contact School & Services Secondary update

---

_primary/Staff Contact.md

updated cheong_ju_li_geraldinne_a@moe.edu.sg to geraldine_cheong@moe.edu.sg

Update Staff List

---

_secondary/Staff Contact.md

Removal of Tang Kum Leong James

Secondary Staff Contact update

---

_staff/Secondary Section.md

Request from Yong Howe:
- 'School Management Team' changed to 'School Care Team'

To update the school website - Secondary Section

---

_staff/Primary Section.md
_staff/Secondary Section.md

Request from Mr Philip Tan/Steven:
- To update the Principal name for Primary school and Secondary school

To update the Principal name for Primary school and Secondary school 

---

_about/Principal's Foreword.md
_secondary/Talent Development/Music Elective Programme.md
_staff/Primary Section.md

Request from Mr Philip Tan:
- To update the Principal's foreword

To update the Principal's foreword

---

_about/Principal's Foreword.md
_staff/Secondary Section.md

Update of 2025 staff list on school website

---

_prospective-students/Sec Admission/Level 1 Registration.md

To update the Cut off points on the school website - Level 1 (2025) Registration

---

_staff/Primary Section.md

School Pri Staff List updating 

---

_staff/Primary Section.md
_staff/Secondary Section.md

Request from VP Philip Tan and Steven

To update name for VP Philip Tan

---

_advertisement/School Canteen (Primary).md

Amend Chinese Cuisine Stall to 17 Jan 2025

Amend Chinese Cuisine Stall to 17 Jan 2025

---

_non-academic/CCA/CCA Department Teacher's Email Contact.md
_staff/Primary Section.md

Corrected Marissa and Nicholas’ designations, updated CCA staff contact list

Updated Primary Staff List

---

_advertisement/School Canteen (Primary).md
resources/secondary-school-news/_posts/2017-08-09-post-National Day 2017.md

Amend the Chinese Cuisine Stall closing date to 31 Jan 2025, requested by Wei Ping

Change Canteen Advertisement for Malay Stall and Breakfast Stall

---

_advertisement/School Canteen (Primary).md
pages/test.md

Removed Chinese Cuisine stall advertisement as requested

Update of Canteen Advertisement for Malay Stall and Breakfast Stall

---

_dual-track-curriculum/Subjects Offered (IP & SP)/Science.md
_prospective-students/Prospectus (Sec).md
_secondary/Prospectus.md
_secondary/Talent Development/Cnergy Programme.md

Sci Prospectus Version is based on the Later version Jeff sent.

Update of Science propestus based on the later version 

---

_staff/Secondary Section.md

Request from Steven:
- To remove Cheryl Lim from the CHS website - Staff List

To remove Cheryl Lim from the CHS website - Staff List

---

index.md

Removed Ready for School Kit 2024 and Community Bursary Award 2024

Updated Main Landing Page

---

_staff/Primary Section.md
_staff/Secondary Section.md

replaced chs_principal@moe.edu.sg with chs_sch_leaders@moe.edu.sg

Updated School Leaders Email address in Staff Contact list

---

_staff/Secondary Section.md

Request from Steven:
- New Staff: Mr Yip Cheng Hou and Ms Olyna Ong

Update of Staff List on school website

---

_staff/Primary Section.md
_staff/Secondary Section.md

until google group email chs_sch_leaders@moe.edu.sg issue is resolved

updated School leaders email to chs_principal@moe.edu.sg

---

_prospective-students/Direct School Admission (DSA).md
index.md

📱 DSA Updates Status
✅ Completed & Pending Review:
DSA page updates
Home page (DSA 2nd announcement)
Note: Any new changes will be included under this request

2025 DSA Website + Home page 

---

_connect-with-us/Contact School & Services/Overview.md
_staff/Primary Section.md

Updated Student Care details and Staff list

updated contact us list and Staff List

---

_advertisement/School Canteen (Primary).md

Added Chinese Noodle Stall to Canteen Advertisement page

Canteen Advertisement
